### ISSUE TITLE
Add support for mi 9

### ISSUE THREAD

**Issue by eliashuber02** [pelya/android-keyboard-gadget#167]
Same problem as #166 

>  Ad support for Mi 9
> 
> What is not working
> A: None of custom kernels
> 
> What exactly you would like to have / do.
> A: Android Keyboard Gadget, what should I do?

**Comment by nift4** [comment]
Duplicates are not good

**Comment by eliashuber02** [comment]
yes i know, but otherwise it won't get noticed

**Comment by pelya** [comment]
I get notified about every new issue, but since this project is in deep
maintenance mode (I don't want to say abandoned, but yeah), you're on your
own. And anyway, if I don't own the same device, or don't care to void the
warranty by rooting it, there's not much I can do.

**Comment by eliashuber02** [comment]
well that is sad, it would've been nice if there would've been 'official' support for the mi 9, well then i already got an alternative

**Comment by pelya** [comment]
I'd love to have some kind ultra cheap Android device that's available
everywhere, so I could maintain only one version of the kernel and just
tell people to go buy it  instead of building ten different kernels. The
closest thing to that is Amazon Fire tablet, but it's not available
worldwide, and it's price is still not exactly throwaway money.

**Comment by eliashuber02** [comment]
another idea I have would be a ultra cheap bluethooth device you connect your phone to and then connect, said the device to the pc.
that way you would only have to maintain that cheap device
but I don't really have an idea what you could use for that

**Comment by nift4** [comment]
http://inputstick.com/ ?

**Comment by eliashuber02** [comment]
yea basically
