### ISSUE TITLE
Not understanding readme

### ISSUE THREAD

**Issue by Leedl3** [pelya/android-keyboard-gadget#48]
Hi, I am trying to port this patch to the Moto E 2nd Gen "surnia". The kernel piece is fine its the boot.img piece I am skeptical about. This will need to be installed using fastboot right? Also the command: repo init -u https://android.googlesource.com/platform/manifest -b android-4.4.2_r1 . What would I need to change the android-4.4.2_r1 to? I am running cm 13 witch is android version 6.0.1. I do apologize if the answer to these questions are simple but I want to be sure that I don't mess up especially since this is the boot.img file we are talking about.

Thank you
-Leedl3

**Comment by pelya** [comment]
These instructions are for AOSP. If you are using cyanogenmod, first you
need to compile cyanogenmod itself:
https://wiki.cyanogenmod.org/w/Build_for_surnia
Then you patch the kernel, recompile your cyanogenmod, and take the
resulting boot.img, which you can flash using fastboot.
You don't need system.img and other stuff, but unfortunately it will
compile everything, so that requirement to have 60Gb free space still
applies.

And if you succeed, please give me compiled boot.img.

**Comment by Leedl3** [comment]
Ok, thank you!

**Comment by conrad-heimbold** [comment]
Newer tutorial: https://wiki.lineageos.org/devices/surnia/build
