### ISSUE TITLE
add keystrokes for app

### ISSUE THREAD

**Issue by tim241** [pelya/android-keyboard-gadget#53]
hello @pelya I have a question:
I am creating a hid app but I don't want to work with the hid-gadget-test file. Is it possible to build it into my app to send keystrokes from your hid patch?(I am using xamarin(mono for android/ C# for android)
Regards,
Tim

**Comment by pelya** [comment]
Yes, you just open /dev/hidg0 as a regular file, and write into it. Here's
a piece of code that does this:
https://github.com/pelya/android-keyboard-gadget/blob/master/hid-gadget-test/jni/hid-gadget-test.c#L178
The format of the bytes sent is described in readme:
https://github.com/pelya/android-keyboard-gadget#how-it-works

Because of SELinux, Android app cannot open the file directly, so it
launches su and pipes data through it, something like FILE *pipe =
popen("su"); fprintf(pipe, "cat > /dev/hidg0\n"); then write keycodes to
pipe, and don't forget to fflush().

**Comment by tim241** [comment]
If Selinux is diabled I
can do someting like this right?:
Echo 0x01 | /dev/hidg0

**Comment by pelya** [comment]
Yes you can.

**Comment by tim241** [comment]
can you give me some more details about that " FILE *pipe =
popen("su"); fprintf(pipe, "cat > /dev/hidg0\n"); then write keycodes to
pipe, and don't forget to fflush()."? the command does not seems to work. ANd I am not understanding it.

**Comment by pelya** [comment]
It's a piece of C code, I don't know how are you doing file writing in C#.
Open /dev/hidg0 and write into it chunks 8 bytes each, flush the buffer
after each write, that's it.

**Comment by tim241** [comment]
if I create a test file(located on sdcard with: 0x0a in it) if I do a root shell and then: cat /sdcard/test > /dev/hidg0 but then it spams an random key from my keyboard, any idea?

**Comment by tim241** [comment]
or can you explain how to do it with the terminal? Because I can easilly send shell commands like cat in su.

**Comment by pelya** [comment]
Yes, you can copypaste a text file.
Please read the keyboard protocol description at
https://github.com/pelya/android-keyboard-gadget#how-it-works
You send 8 bytes at once, not 1, and the first byte is special.

**Comment by tim241** [comment]
I still don't understand it :-(

**Comment by tim241** [comment]
nevermind, I will use the hid-gadget test utillity :-)
