### ISSUE TITLE
Nexus 7 2012 Marshmallow boot image

### ISSUE THREAD

**Issue by mateosss** [pelya/android-keyboard-gadget#71]
First of all, pretty awesome project.

My nexus 7 2012 Wifi, has installed this rom 

https://forum.xda-developers.com/nexus-7/development/rom-6-0-android-marshmallow-pure-aosp-t3226012

Is there any possibilities for the boot.img in this repo to work if I flash it? 

Thanks

**Comment by pelya** [comment]
No, boot.img should be compiled individually for a particular system.

It might boot with a bit of luck, since Nexus 7 kernel changes so
infrequently.


On Jan 5, 2017 3:46 PM, "Mateo de Mayo" <notifications@github.com> wrote:

First of all, pretty awesome project.

My nexus 7 2012 Wifi, has installed this rom

https://forum.xda-developers.com/nexus-7/development/rom-6-
0-android-marshmallow-pure-aosp-t3226012

Is there any possibilities for the boot.img in this repo to work if I flash
it?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pelya/android-keyboard-gadget/issues/71>, or mute the
thread
