### ISSUE TITLE
Possibility to deactivate HID

### ISSUE THREAD

**Issue by ChrisGCode** [pelya/android-keyboard-gadget#9]
Is it possible to deactivate HID?
It think it should be possible to activate/deactivate it like mtp, mass_store, ...

**Comment by lars18th** [comment]
Hi,

I applied the patch for kernel 3.4. Now I found directory "/sys/class/android_usb/android0/f_hid" in my phone, but NO "/dev/hidg0" or "/dev/hidg1".

$ cat /sys/class/android_usb/android0/functions
mpt,adb

I need to modify "init.usb.rc" to enable HID-Gadget mode?
How I can debug if the proper init funcion is executed?

**Comment by pelya** [comment]
If you modified the patch, you need to enable HID mode by hand. Until then,
there will be no /dev/hidg0 and hidg1.
Execute following commands in the root shell:

echo 0 > /sys/class/android_usb/android0/enable

echo mtp,adb,hid > /sys/class/android_usb/android0/functions

echo 1 > /sys/class/android_usb/android0/enable

You habe to do that each time you plug a cable to USB post, because Android
system will override HID mode with just 'mtp,adb'.

**Comment by lars18th** [comment]
Thank you for the comment!

But, I don't "modified" the patch. See the code here:
http://github.com/Al3XKOoL/tinno82_S5501/commit/d6ff89b081fbd61ed3ce542f1c886d9180439433

I first try this. I created this file and executed it as root:
-------------------8<--------------------
#!/system/bin/sh

echo 0 > /sys/class/android_usb/android0/enable
echo mtp,adb,hid > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
-------------------8<--------------------
This not enables/creates "/dev/hidg*

Any other idea about what happens?
Please, remember that "/sys/class/android_usb/android0/f_hid" exists!

**Comment by lars18th** [comment]
Hi Pelya,

Yes, the patch is using the "hid_enabled" check.

But when I execute this script as root:

#!/system/bin/sh
echo 0 > /sys/class/android_usb/android0/enable
echo mtp,adb,hid > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable 

The adb disconnects, no MPT, and no HID devices.
Where you think is the trouble?

**Comment by alandewayne** [comment]
Stop fucking sending me those emails

**Comment by pelya** [comment]
@alandewayne you are watching this repository, that's why you are getting
all these emails - https://github.com/pelya/android-keyboard-gadget/watchers
Press 'unwatch' button at this webpage to stop receiving them.

**Comment by pelya** [comment]
@lars18th  replace lines

if (hid_enabled)
    android_enable_function(dev, "hid");

with just

 android_enable_function(dev, "hid");

Then it will always be enabled. I've removed that 'hid_enabled' check some time ago from all my patches, but the old version of the patch still flies around the net.

**Comment by lars18th** [comment]
Hi Pelya,

With current version of the kernel (without the line "if (hid_enabled)") the HID-Gadget patch is working: I can send keystrokes using the tool hid-gadget-test.

However, I have found a problem with the current patch. I comment the problem:

- By default, the USB mode in my Android device (with the patch applied) is: mpt,adb,hid. Because I need to connect the Android device to a very buggy USB device, I like to enable ONLY keyboard and mouse emulation over the USB connection. Then I execute these commands from the shell (as root):

$ echo 0 > /sys/class/android_usb/android0/enable
$ echo hid > /sys/class/android_usb/android0/functions
$ echo 1 > /sys/class/android_usb/android0/enable

And when I execute the last line the Android device freezes. Only with a hard-reboot (remove battery) I can restore it.

You know where is the problem?
Thank you for your time!

**Comment by pelya** [comment]
No, I never tried to use it this way. Looks like you'll need to add
printk() to each function, and trace where it freezes. Or you can try to
debug it -
http://stackoverflow.com/questions/17477258/how-to-use-gdbclient-to-debug-the-kernel-on-nexus-7

**Comment by pelya** [comment]
Maybe you are initializing HID module twice? There is already one explicit
initialization inside enable_functions(), and when you do

echo hid > /sys/class/android_usb/android0/functions

there is another initialization.

**Comment by lars18th** [comment]
Hi Pelya,

After weeks using a kernel with your patch applied, I found that in some cases the kernel hangs when changing the USB mode. I suggest that you reimplement a safe mode for enable/disable HID mode. Perhaps this can be complex, but it minimizes the cases of a crash.

Regards!

**Comment by conrad-heimbold** [comment]
Answer has been given: to deactivate HID; 
1. compile with android_enable_function() commented out
2. Execute in root shell (replace $FUNCTION with what you would like to have): 
echo 0 > /sys/class/android_usb/android0/enable
echo $FUNCTION > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable

Possible functions are adb, mtp, midi, ptp, charging, ffs, hid; seperated with a comma (,) and no whitespace.
