### ISSUE TITLE
Add please patch for linux kernel 3.0.101

### ISSUE THREAD

**Issue by Staskkk** [pelya/android-keyboard-gadget#90]
I have Galaxy S3 mini I8190 with custom ROM OS 4.4.4 and kernel 3.0.101 from here http://novafusion.pl/downloads/ . Is it possible to do patch for this kernel?

**Comment by tim241** [comment]
We need the kernel source code to make a patch, link us to the source code and then people could make a patch.

**Comment by conrad-heimbold** [comment]
You can try the general kernel patch for [kernel version 3.01](https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.01.patch)

I8190 uses some special SoC (ST-Ericsson NovaThor U8500). We don't have a patch specifically for that architecture, because it seems to be very rare.

**Comment by conrad-heimbold** [comment]
No answer since 5 days, therefore closing.
